image: python:3.8

test:
  stage: test
  script:
    - python tests.py

test3.6:
  image: python:3.6
  stage: test
  script:
    - python tests.py

checks:
  script:
    - pip install flake8
    - flake8 --ignore=E731,W504
